[package]
name = "elmdb_nif"
version = "0.1.0"
edition = "2021"

[lib]
name = "elmdb_nif"
crate-type = ["cdylib"]

[dependencies]
rustler = { version = "0.37.3", features = ["nif_version_2_16"] }
bitflags = "2.6"
chacha20poly1305 = "0.10"
libc = "0.2"
lmdb-master3-sys = "0.2.6"
lazy_static = "1.4"
arc-swap = "1"
scc = "3"
ahash = "0.8.12"
